version: "3"
services:
  tt-rss:
    image: linuxserver/tt-rss
    container_name: tt-rss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asian/Shanghai
    volumes:
      - /home/username/docker/tts:/config
    ports:
      - 8080:80
    restart: unless-stopped

  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: databass

  servicersshub:
    image: diygod/rsshub
    restart: always
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://dbredis:6379/'
      CACHE_EXPIRE: 3600
      PUPPETEER_WS_ENDPOINT: 'ws://servicebrowserless:3000'
      LISTEN_INADDR_ANY: 1
    depends_on:
      - dbredis
      - servicebrowserless

  servicebrowserless:
    image: browserless/chrome
    restart: always

  dbredis:
    image: redis
    restart: always